defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  min_messages: WARNING

development:
  <<: *defaults
  database: barcamplive_development

test:
  <<: *defaults
  database: barcamplive_test

production:
  <<: *defaults
  database: barcamplive_development
